### PR TITLE
Images

### PR DESCRIPTION
**Pull request by SDGGiesbrecht**
This demonstrates how to insert an image.

Your URLs were local ones. `/Users/Kel/Downloads/WEBSITE COVER.jpg` pointed at the downloads directory on your computer. No one else’s device can see that.

I created a `Template/Images` directory in the repository. Anything you put there (such as the flag that is there to demonstrate) will be copied into the `Images` directory of the generated website. That generated directory is where you need to point each `src` URL to, like I did [here](https://github.com/keeliejin/Thessaloniki-website/commit/f0737b44f772cadbde1e983a8dfaea4d2ad4abbf#diff-7d5a5df2dabe962b971b80885d810e5aR4).

Since I have no idea what is in your downloads folder, I cannot insert the real images. You will have to do that yourself.

Every `img` tag needs an `alt` attribute, which is the text that will be read by screen readers (such as for blind people). It will also be displayed if the user has disabled images to make their internet connection faster if, say, they live in Timbuktu and need to boat out into the lake, stand on tiptoe and hold an antenna in the air just to get a sluggish signal. (I am not kidding. Life in the Canadian wild can be weird sometimes.) Lastly, Google can search the text easily, but cannot search the image very well.

You have duplicated the same thing for both languages on each page. When the image needs to be different, you can do that. But if it is the same image for both, just put it outside the `[* ... *]` and it will not be localized. Just include a smaller localized section inside the `alt` attribute like I did.

Once you insert the real images, I can take another look to see what the point in the `width`, `height` and `border` was. Usually those sorts of things are best done [with CSS instead](https://www.w3schools.com/cssref/pr_dim_width.asp), which is why I left them out. But without any images to look at, I cannot say for sure.

### CODE REVIEW

**Comment by SDGGiesbrecht** [comment]
You can do `git pull`, then `git checkout images` to get this branch onto your device so you work on it locally.

**Comment by keeliejin** [comment]
@SDGGiesbrecht

Wow, it has taken me a long time to get back to this :/ Ok, I added some images. Please let me know your thoughts. Thanks again so much for your continued help with this :)

**Review by SDGGiesbrecht — COMMENTED** [review]
The images look nice.

I noticed two slight things we do not see when we load it on our Macs, but that would cause issues when it is online:

1. There is an extra slash. `[*site root*]` already contains a trailing slash when it is expanded, so `[*site root*]/Images` ends up with two: `..//Images`.

2. Spaces aren’t valid in a URL. You have to escape them using `%20`, where “20” is the hexadecimal code of the space character: `Images/WEBSITE%20COVER.jpg`.

Both apply to every new image. And apparently there are some spaces I failed to notice in other links from before. Paste the code (right‐click the file in the `Result` directory, open it in Xcode or TextEdit instead of Safari, ⌘A to select all of it, and ⌘C to copy) into the following HTML validator and it will highlight all the invalid spaces for you: https://validator.w3.org/nu/#textarea.

**Comment by keeliejin** [comment]
Ok, so when I find these errors, do I change them in the files in the
results directory?

**Comment by SDGGiesbrecht** [comment]
> [D]o I change them in the files in the results directory?

No. The various pieces in the `Template` directory are automatically assembled into the finished product in the `Result` directory. The result is what the validator needs to look over (because that is the only code it understands), but the template pieces are where you need to actually do the fixes.

If you were to just make the changes in the `Result` directory, they would be overwritten and reverted the next time you generated the site.

**Comment by keeliejin** [comment]
Ok, how do I get rid of the double slashes when my computer doesn't see
them?

**Comment by SDGGiesbrecht** [comment]
One slash is automatically added by the generator, the other is in the template file. Just remove the one in the template file.

**Comment by keeliejin** [comment]
Ok, thanks, Jeremy

**Comment by keeliejin** [comment]
@SDGGiesbrecht
Ok, I think I did the things that needed to be changed for this branch. Is it possible to create/edit two different branches before merging on or the other of them? Or is that just asking for trouble
?

**Comment by SDGGiesbrecht** [comment]
The *links* are correct now, but only for the old file names. `<a href="Some%20File.html">` gets translated by the web server to `Some File.html`. So escape *links* with `%`, but leave the *file names* they point at in their natural state.

I will try and fix that for you. This one was my fault for explaining it poorly the first time.

***

> Is it possible to create/edit two different branches before merging on or the other of them? Or is that just asking for trouble?

Yes. If the branches only affect different lines of code from each other, you won’t even notice.

If the separate branches involve changes to the same lines of code it can become more complicated, but even then it is not impossible.

**Comment by SDGGiesbrecht** [comment]
That should be right now.

**Comment by keeliejin** [comment]
Sweet, thanks!

**Pull request merged**
